eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-hi

#ribbon:
#  ConnetcTimeout: 1200
#  readTime: 300
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 2
#  OkToRetryOnAllOperations: true